import { ICreateRoleRequest, RoleTypeEnum, ModuleNameEnum } from '@/types';

/**
 * Permission Matrix Templates
 * Pre-configured role templates based on common access patterns
 */

/**
 * Super Admin - Full access across company
 */
export const SUPER_ADMIN_ROLE_TEMPLATE: ICreateRoleRequest = {
    roleName: 'Administrator',
    description: 'Full system access with all permissions',
    roleType: RoleTypeEnum.EMPLOYEE,
    permissionMatrix: [
        {
            moduleName: ModuleNameEnum.USERS,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.COMPANY,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.BRANCH,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.ROLES,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.PERMISSIONS,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.DOCUMENTS,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        // {
        //     moduleName: ModuleNameEnum.QUEUES,
        //     create: true,
        //     read: true,
        //     update: true,
        //     delete: true,
        //     approve: true,
        //     reject: true,
        //     export: true,
        // },
        {
            moduleName: ModuleNameEnum.UPLOAD,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.REPORTS,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.SETTINGS,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.PAYROLL,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.ADVANCE,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.LOT,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.VISA_MANAGER,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
    ],
};

/**
 * Branch Manager - Branch-level CRUD with approvals
 */
export const BRANCH_MANAGER_ROLE_TEMPLATE: ICreateRoleRequest = {
    roleName: 'Branch Manager',
    description: 'Branch-level CRUD operations with approval rights',
    roleType: RoleTypeEnum.EMPLOYEE,
    permissionMatrix: [
        {
            moduleName: ModuleNameEnum.USERS,
            create: true,
            read: true,
            update: true,
            delete: false,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.BRANCH,
            create: false,
            read: true,
            update: true,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.DOCUMENTS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.REPORTS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.PAYROLL,
            create: false,
            read: true,
            update: true,
            delete: false,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.VISA_MANAGER,
            create: false,
            read: true,
            update: true,
            delete: false,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.UPLOAD,
            create: true,
            read: true,
            update: true,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.COMPANY,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.ROLES,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.PERMISSIONS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.SETTINGS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.ADVANCE,
            create: false,
            read: true,
            update: true,
            delete: false,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.LOT,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
    ],
};

/**
 * Visa Manager - Visa and quota management only
 */
export const VISA_MANAGER_ROLE_TEMPLATE: ICreateRoleRequest = {
    roleName: 'Visa Manager',
    description: 'Manages visa documents and LOT quotas with limited access',
    roleType: RoleTypeEnum.EMPLOYEE,
    permissionMatrix: [
        {
            moduleName: ModuleNameEnum.VISA_MANAGER,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.LOT,
            create: true,
            read: true,
            update: true,
            delete: true,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.USERS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.DOCUMENTS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.BRANCH,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.REPORTS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.UPLOAD,
            create: true,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
    ],
};

/**
 * HR Executive - Employee CRUD with limited access
 */
export const HR_EXECUTIVE_ROLE_TEMPLATE: ICreateRoleRequest = {
    roleName: 'HR Executive',
    description: 'Limited employee management and HR operations',
    roleType: RoleTypeEnum.EMPLOYEE,
    permissionMatrix: [
        {
            moduleName: ModuleNameEnum.USERS,
            create: true,
            read: true,
            update: true,
            delete: false,
            approve: false,
            reject: false,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.DOCUMENTS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: true,
            reject: true,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.PAYROLL,
            create: false,
            read: true,
            update: true,
            delete: false,
            approve: false,
            reject: false,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.UPLOAD,
            create: true,
            read: true,
            update: true,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.REPORTS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.BRANCH,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.COMPANY,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.ROLES,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.PERMISSIONS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.SETTINGS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.ADVANCE,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: true,
        },
        {
            moduleName: ModuleNameEnum.VISA_MANAGER,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.LOT,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
    ],
};

/**
 * Employee - Self-service only
 */
export const EMPLOYEE_ROLE_TEMPLATE: ICreateRoleRequest = {
    roleName: 'Employee',
    description: 'Self-service access for employees',
    roleType: RoleTypeEnum.EMPLOYEE,
    permissionMatrix: [
        {
            moduleName: ModuleNameEnum.USERS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.COMPANY,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.BRANCH,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.DOCUMENTS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.UPLOAD,
            create: true,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.REPORTS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.ROLES,
            create: false,
            read: false,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.PERMISSIONS,
            create: false,
            read: false,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
        {
            moduleName: ModuleNameEnum.SETTINGS,
            create: false,
            read: true,
            update: false,
            delete: false,
            approve: false,
            reject: false,
            export: false,
        },
    ],
};

/**
 * Get all role templates
 */
export const ROLE_TEMPLATES = {
    SUPER_ADMIN: SUPER_ADMIN_ROLE_TEMPLATE,
    BRANCH_MANAGER: BRANCH_MANAGER_ROLE_TEMPLATE,
    VISA_MANAGER: VISA_MANAGER_ROLE_TEMPLATE,
    HR_EXECUTIVE: HR_EXECUTIVE_ROLE_TEMPLATE,
    EMPLOYEE: EMPLOYEE_ROLE_TEMPLATE,
};

/**
 * Get role template by name
 */
export function getRoleTemplate(templateName: keyof typeof ROLE_TEMPLATES): ICreateRoleRequest {
    return ROLE_TEMPLATES[templateName];
}
