export interface CountryCode {
  code: string;
  name: string;
  dial_code: string;
}

// Comprehensive list of country codes sorted by name
// Note: Some dial codes like +1 are shared by multiple countries (US, Canada, etc.)
export const COUNTRY_CODES: CountryCode[] = [
  { "code": "AF", "name": "Afghanistan", "dial_code": "+93" },
  { "code": "AL", "name": "Albania", "dial_code": "+355" },
  { "code": "DZ", "name": "Algeria", "dial_code": "+213" },
  { "code": "AD", "name": "Andorra", "dial_code": "+376" },
  { "code": "AO", "name": "Angola", "dial_code": "+244" },
  { "code": "AR", "name": "Argentina", "dial_code": "+54" },
  { "code": "AM", "name": "Armenia", "dial_code": "+374" },
  { "code": "AU", "name": "Australia", "dial_code": "+61" },
  { "code": "AT", "name": "Austria", "dial_code": "+43" },
  { "code": "AZ", "name": "Azerbaijan", "dial_code": "+994" },
  { "code": "BH", "name": "Bahrain", "dial_code": "+973" },
  { "code": "BD", "name": "Bangladesh", "dial_code": "+880" },
  { "code": "BY", "name": "Belarus", "dial_code": "+375" },
  { "code": "BE", "name": "Belgium", "dial_code": "+32" },
  { "code": "BT", "name": "Bhutan", "dial_code": "+975" },
  { "code": "BR", "name": "Brazil", "dial_code": "+55" },
  { "code": "BN", "name": "Brunei", "dial_code": "+673" },
  { "code": "BG", "name": "Bulgaria", "dial_code": "+359" },
  { "code": "KH", "name": "Cambodia", "dial_code": "+855" },
  { "code": "CA", "name": "Canada", "dial_code": "+1" },
  { "code": "CL", "name": "Chile", "dial_code": "+56" },
  { "code": "CN", "name": "China", "dial_code": "+86" },
  { "code": "CO", "name": "Colombia", "dial_code": "+57" },
  { "code": "CR", "name": "Costa Rica", "dial_code": "+506" },
  { "code": "HR", "name": "Croatia", "dial_code": "+385" },
  { "code": "CU", "name": "Cuba", "dial_code": "+53" },
  { "code": "CY", "name": "Cyprus", "dial_code": "+357" },
  { "code": "CZ", "name": "Czech Republic", "dial_code": "+420" },
  { "code": "DK", "name": "Denmark", "dial_code": "+45" },
  { "code": "EG", "name": "Egypt", "dial_code": "+20" },
  { "code": "EE", "name": "Estonia", "dial_code": "+372" },
  { "code": "ET", "name": "Ethiopia", "dial_code": "+251" },
  { "code": "FI", "name": "Finland", "dial_code": "+358" },
  { "code": "FR", "name": "France", "dial_code": "+33" },
  { "code": "GE", "name": "Georgia", "dial_code": "+995" },
  { "code": "DE", "name": "Germany", "dial_code": "+49" },
  { "code": "GH", "name": "Ghana", "dial_code": "+233" },
  { "code": "GR", "name": "Greece", "dial_code": "+30" },
  { "code": "HK", "name": "Hong Kong", "dial_code": "+852" },
  { "code": "HU", "name": "Hungary", "dial_code": "+36" },
  { "code": "IS", "name": "Iceland", "dial_code": "+354" },
  { "code": "IN", "name": "India", "dial_code": "+91" },
  { "code": "ID", "name": "Indonesia", "dial_code": "+62" },
  { "code": "IR", "name": "Iran", "dial_code": "+98" },
  { "code": "IQ", "name": "Iraq", "dial_code": "+964" },
  { "code": "IE", "name": "Ireland", "dial_code": "+353" },
  { "code": "IL", "name": "Israel", "dial_code": "+972" },
  { "code": "IT", "name": "Italy", "dial_code": "+39" },
  { "code": "JP", "name": "Japan", "dial_code": "+81" },
  { "code": "JO", "name": "Jordan", "dial_code": "+962" },
  { "code": "KZ", "name": "Kazakhstan", "dial_code": "+7" },
  { "code": "KE", "name": "Kenya", "dial_code": "+254" },
  { "code": "KW", "name": "Kuwait", "dial_code": "+965" },
  { "code": "KG", "name": "Kyrgyzstan", "dial_code": "+996" },
  { "code": "LA", "name": "Laos", "dial_code": "+856" },
  { "code": "LV", "name": "Latvia", "dial_code": "+371" },
  { "code": "LB", "name": "Lebanon", "dial_code": "+961" },
  { "code": "LY", "name": "Libya", "dial_code": "+218" },
  { "code": "LT", "name": "Lithuania", "dial_code": "+370" },
  { "code": "LU", "name": "Luxembourg", "dial_code": "+352" },
  { "code": "MY", "name": "Malaysia", "dial_code": "+60" },
  { "code": "MV", "name": "Maldives", "dial_code": "+960" },
  { "code": "MT", "name": "Malta", "dial_code": "+356" },
  { "code": "MX", "name": "Mexico", "dial_code": "+52" },
  { "code": "MD", "name": "Moldova", "dial_code": "+373" },
  { "code": "MC", "name": "Monaco", "dial_code": "+377" },
  { "code": "MN", "name": "Mongolia", "dial_code": "+976" },
  { "code": "ME", "name": "Montenegro", "dial_code": "+382" },
  { "code": "MA", "name": "Morocco", "dial_code": "+212" },
  { "code": "MM", "name": "Myanmar", "dial_code": "+95" },
  { "code": "NP", "name": "Nepal", "dial_code": "+977" },
  { "code": "NL", "name": "Netherlands", "dial_code": "+31" },
  { "code": "NZ", "name": "New Zealand", "dial_code": "+64" },
  { "code": "NG", "name": "Nigeria", "dial_code": "+234" },
  { "code": "NO", "name": "Norway", "dial_code": "+47" },
  { "code": "OM", "name": "Oman", "dial_code": "+968" },
  { "code": "PK", "name": "Pakistan", "dial_code": "+92" },
  { "code": "PS", "name": "Palestine", "dial_code": "+970" },
  { "code": "PA", "name": "Panama", "dial_code": "+507" },
  { "code": "PE", "name": "Peru", "dial_code": "+51" },
  { "code": "PH", "name": "Philippines", "dial_code": "+63" },
  { "code": "PL", "name": "Poland", "dial_code": "+48" },
  { "code": "PT", "name": "Portugal", "dial_code": "+351" },
  { "code": "QA", "name": "Qatar", "dial_code": "+974" },
  { "code": "RO", "name": "Romania", "dial_code": "+40" },
  { "code": "RU", "name": "Russia", "dial_code": "+7" },
  { "code": "SA", "name": "Saudi Arabia", "dial_code": "+966" },
  { "code": "RS", "name": "Serbia", "dial_code": "+381" },
  { "code": "SG", "name": "Singapore", "dial_code": "+65" },
  { "code": "SK", "name": "Slovakia", "dial_code": "+421" },
  { "code": "SI", "name": "Slovenia", "dial_code": "+386" },
  { "code": "ZA", "name": "South Africa", "dial_code": "+27" },
  { "code": "KR", "name": "South Korea", "dial_code": "+82" },
  { "code": "ES", "name": "Spain", "dial_code": "+34" },
  { "code": "LK", "name": "Sri Lanka", "dial_code": "+94" },
  { "code": "SE", "name": "Sweden", "dial_code": "+46" },
  { "code": "CH", "name": "Switzerland", "dial_code": "+41" },
  { "code": "SY", "name": "Syria", "dial_code": "+963" },
  { "code": "TW", "name": "Taiwan", "dial_code": "+886" },
  { "code": "TJ", "name": "Tajikistan", "dial_code": "+992" },
  { "code": "TZ", "name": "Tanzania", "dial_code": "+255" },
  { "code": "TH", "name": "Thailand", "dial_code": "+66" },
  { "code": "TR", "name": "Turkey", "dial_code": "+90" },
  { "code": "TM", "name": "Turkmenistan", "dial_code": "+993" },
  { "code": "UG", "name": "Uganda", "dial_code": "+256" },
  { "code": "UA", "name": "Ukraine", "dial_code": "+380" },
  { "code": "AE", "name": "United Arab Emirates", "dial_code": "+971" },
  { "code": "GB", "name": "United Kingdom", "dial_code": "+44" },
  { "code": "US", "name": "United States", "dial_code": "+1" },
  { "code": "UY", "name": "Uruguay", "dial_code": "+598" },
  { "code": "UZ", "name": "Uzbekistan", "dial_code": "+998" },
  { "code": "VE", "name": "Venezuela", "dial_code": "+58" },
  { "code": "VN", "name": "Vietnam", "dial_code": "+84" },
  { "code": "YE", "name": "Yemen", "dial_code": "+967" },
  { "code": "ZM", "name": "Zambia", "dial_code": "+260" },
  { "code": "ZW", "name": "Zimbabwe", "dial_code": "+263" }
];
